var ABA_CASOS = 'CASOS';


var SCHEMA_CABINE_VERDE = obterSchemaCabineVerdeUnificado_();
var COLUNAS_CASOS = SCHEMA_CABINE_VERDE.CASOS;
var COLUNAS_TRIAGEM_RESPOSTAS = SCHEMA_CABINE_VERDE.TRIAGEM_RESPOSTAS;
var COLUNAS_EVENTOS_OCORRENCIA = SCHEMA_CABINE_VERDE.EVENTOS_CASO;
var COLUNAS_INDICADORES_OPERACIONAIS = SCHEMA_CABINE_VERDE.INDICADORES_OPERACIONAIS;
