var ABA_CASOS = 'CASOS';


var COLUNAS_CASOS = CABINE_VERDE_SCHEMA.CASOS;
var COLUNAS_TRIAGEM_RESPOSTAS = CABINE_VERDE_SCHEMA.TRIAGEM_RESPOSTAS;
var COLUNAS_EVENTOS_OCORRENCIA = CABINE_VERDE_SCHEMA.EVENTOS_CASO;
var COLUNAS_INDICADORES_OPERACIONAIS = CABINE_VERDE_SCHEMA.INDICADORES_OPERACIONAIS;
