import { useEffect, useMemo, useState } from 'react';

type Operador = { email: string; nome: string };
type Modo = 'completo' | 'formulario' | 'resumo';
type EquipePlantao = 'Equipe 1' | 'Equipe 2';

const campos: [string, string][] = [['analiseCadastros', 'Análise de cadastros (190)'], ['contatosDeclarantes', 'Contatos com declarantes'], ['localizacoesTalao', 'Localizações/baixas por talão'], ['transferencias6190', 'Transferências ao ramal 6190'], ['coletaFotos', 'Coleta de mídia/foto'], ['transferenciaAudio', 'Transferência de áudio do 190'], ['atualizacoesSiopm', 'Atualização do histórico no SIOPM Web'], ['ocorrenciasGeradas', 'Ocorrências geradas']];
const equipes: { nome: EquipePlantao; horario: string }[] = [{ nome: 'Equipe 1', horario: '07h às 19h' }, { nome: 'Equipe 2', horario: '19h às 07h' }];
const hoje = () => new Date().toISOString().slice(0, 10);
const chaveBanco = (campo: string) => campo.replace(/[A-Z]/g, letra => `_${letra.toLowerCase()}`);
const valor = (registro: any, campo: string) => Number(registro[campo] ?? registro[chaveBanco(campo)] ?? 0);
const nomeEquipe = (registro: any): string => registro.equipePlantao ?? registro.equipe_plantao ?? 'Sem equipe informada';
const formatarData = (data: string) => new Date(`${data}T12:00:00`).toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' });

export default function ProducaoDiaria({ api, operador, modo = 'completo' }: { api: any; operador: Operador; modo?: Modo }) {
  const [data, setData] = useState(hoje()); const [filtroData, setFiltroData] = useState(hoje()); const [filtroEquipe, setFiltroEquipe] = useState('todas'); const [registros, setRegistros] = useState<any[]>([]); const [form, setForm] = useState<any>({ data: hoje(), operadorEmail: operador.email, operadorNome: operador.nome, equipePlantao: 'Equipe 1', estagiario: '', observacao: '' }); const [mensagem, setMensagem] = useState('');
  const carregar = async () => setRegistros(await api.listarProducaoDiaria({ inicio: filtroData, fim: filtroData }));
  useEffect(() => { if (modo !== 'formulario') carregar().catch(erro => setMensagem(`Não foi possível consultar a produção: ${erro.message}`)); }, [filtroData, modo]);
  useEffect(() => { const existente = registros.find(item => item.data === data && String(item.operadorEmail ?? item.operador_email) === operador.email); setForm(existente ? { ...existente, operadorEmail: operador.email, operadorNome: operador.nome, equipePlantao: nomeEquipe(existente) === 'Sem equipe informada' ? 'Equipe 1' : nomeEquipe(existente) } : { data, operadorEmail: operador.email, operadorNome: operador.nome, equipePlantao: 'Equipe 1', estagiario: '', observacao: '' }); }, [data, registros, operador]);
  const total = (registro: any) => campos.reduce((soma, [campo]) => soma + valor(registro, campo), 0); const registrosVisiveis = useMemo(() => filtroEquipe === 'todas' ? registros : registros.filter(item => nomeEquipe(item) === filtroEquipe), [filtroEquipe, registros]); const totais = (lista: any[]) => campos.map(([campo, titulo]) => ({ titulo, total: lista.reduce((soma, item) => soma + valor(item, campo), 0) })); const alterar = (campo: string, valorCampo: any) => setForm((atual: any) => ({ ...atual, [campo]: valorCampo }));
  const salvar = async () => { setMensagem(''); const resposta = await api.salvarProducaoDiaria({ ...form, data, operadorEmail: operador.email, operadorNome: operador.nome }); setMensagem(resposta.ok ? (resposta.atualizado ? 'Produção atualizada sem duplicidade.' : 'Produção salva no banco.') : resposta.mensagem || 'Não foi possível salvar.'); if (resposta.ok && modo !== 'formulario') carregar(); };
  const formulario = <div className="painel painel-producao-diaria"><div className="grade-form"><label>Data<input type="date" value={data} onChange={e => { setData(e.target.value); alterar('data', e.target.value); }} /></label><label>Operador responsável<input value={operador.nome} readOnly /></label><label>Equipe de plantão<select value={form.equipePlantao || 'Equipe 1'} onChange={e => alterar('equipePlantao', e.target.value)}>{equipes.map(equipe => <option key={equipe.nome} value={equipe.nome}>{equipe.nome} — {equipe.horario}</option>)}</select></label><label>Estagiário<input value={form.estagiario || ''} onChange={e => alterar('estagiario', e.target.value)} placeholder="Opcional" /></label>{campos.map(([campo, titulo]) => <label key={campo}>{titulo}<input type="number" min="0" step="1" value={valor(form, campo)} onChange={e => alterar(campo, Math.max(0, Number(e.target.value)))} /></label>)}</div><label>Observação detalhada<textarea value={form.observacao || ''} onChange={e => alterar('observacao', e.target.value)} /></label><button className="primario" onClick={salvar}>Salvar produção do dia</button>{mensagem && <p className="mensagem-salvamento">{mensagem}</p>}</div>;
  const cartoesEquipe = equipes.map(equipe => { const lista = registros.filter(item => nomeEquipe(item) === equipe.nome); const totalEquipe = lista.reduce((soma, item) => soma + total(item), 0); return <article className="resumo-equipe" key={equipe.nome}><div><span>{equipe.nome}</span><small>{equipe.horario}</small></div><strong>{totalEquipe}</strong><p>{lista.length ? `${lista.length} lançamento${lista.length === 1 ? '' : 's'}` : 'Nenhum lançamento'}</p></article>; });
  const resumo = <div className="resumo-diario"><div className="resumo-controles"><label>Data do resumo<input type="date" value={filtroData} onChange={e => setFiltroData(e.target.value)} /></label><label>Equipe<select value={filtroEquipe} onChange={e => setFiltroEquipe(e.target.value)}><option value="todas">As duas equipes</option>{equipes.map(equipe => <option key={equipe.nome} value={equipe.nome}>{equipe.nome}</option>)}</select></label><button className="botao-copiar-painel" onClick={() => undefined}>Copiar imagem para o WhatsApp</button></div><div className="resumo-diario-painel"><header className="resumo-diario-cabecalho"><div><p className="eyebrow">Cabine Verde · COPOM</p><h3>Resumo diário de produção</h3><p>{formatarData(filtroData)}</p></div><div className="resumo-diario-total"><span>Total do dia</span><strong>{registros.reduce((soma, item) => soma + total(item), 0)}</strong></div></header><section className="resumo-equipes">{cartoesEquipe}</section><section className="resumo-indicadores"><h4>Indicadores do dia{filtroEquipe !== 'todas' ? ` · ${filtroEquipe}` : ''}</h4><div className="grade-cartoes">{totais(registrosVisiveis).map(item => <article className="cartao" key={item.titulo}><span>{item.titulo}</span><strong>{item.total}</strong></article>)}</div></section><div className="resumo-diario-rodape"><span>Turnos de 12 horas · atualização conforme lançamentos gravados</span><span>{registros.length} operador{registros.length === 1 ? '' : 'es'} registrado{registros.length === 1 ? '' : 's'}</span></div></div>{registros.length === 0 && <p className="estado-vazio">Nenhum lançamento para esta data.</p>}</div>;
  if (modo === 'formulario') return <section><div className="cabecalho-secao"><div><p className="eyebrow">Produção individual</p><h3>Preenchimento da produção diária</h3><p>Registre os indicadores do dia e selecione a equipe de plantão responsável.</p></div></div>{formulario}</section>;
  if (modo === 'resumo') return <section><div className="cabecalho-secao"><div><p className="eyebrow">Consulta persistida</p><h2>Resumo diário</h2><p>Quadro pronto para copiar e compartilhar no WhatsApp.</p></div></div>{resumo}</section>;
  return <section><div className="cabecalho-secao"><div><p className="eyebrow">Produção operacional</p><h2>Produção diária</h2></div></div>{formulario}{resumo}</section>;
}
