import type { CasoCompleto, SheetPayload } from '../types/case.js';

const colunasDesaparecidos = [
  'idCaso',
  'dataHoraRegistro',
  'dataServico',
  'turno',
  'equipe',
  'operadorResponsavel',
  'municipio',
  'talaoBopm',
  'statusCaso',
  'nomeCompletoDesaparecido',
  'sexoGenero',
  'idade',
  'faixaEtaria',
  'cpf',
  'rg',
  'nomeMae',
  'dataNascimento',
  'dataHoraUltimaVisualizacao',
  'localUltimaVisualizacao',
  'roupaUltimaVisualizacao',
  'meioTransporte',
  'dadosVeiculo',
  'fotoDisponivel',
  'linkFoto',
  'telefoneDesaparecido',
  'dispositivoLigado',
  'camerasResidencia',
  'camerasUltimoLocal',
  'aptoCabineVerde',
  'nomeSolicitante',
  'vinculoSolicitante',
  'telefoneSolicitante',
  'vulnerabilidade',
  'condicaoMentalCognitivaComportamental',
  'limitacaoFisica',
  'usoMedicacaoEssencial',
  'usoAlcoolOutrasDrogas',
  'historicoDesaparecimentoAnterior',
  'conflitoPrevio',
  'suspeitaCrime',
  'locaisHabituais',
  'buscasPreliminares',
  'classificacaoRisco',
  'prioridade',
  'acaoSugerida',
  'localizado',
  'dataHoraLocalizacao',
  'formaLocalizacao',
  'encerrado190',
  'numeroBo',
  'observacoesOperacionais'
] as const;

const hojeIso = (dataHoraRegistro: string): string => {
  const data = new Date(dataHoraRegistro || Date.now());
  if (Number.isNaN(data.getTime())) {
    return new Date().toISOString().slice(0, 10);
  }

  return data.toISOString().slice(0, 10);
};

export const gerarPayloadSheets = (caso: CasoCompleto): SheetPayload => {
  const dados = {
    idCaso: caso.id,
    dataHoraRegistro: caso.dataHoraRegistro,
    dataServico: hojeIso(caso.dataHoraRegistro),
    turno: '',
    equipe: 'Cabine Verde',
    operadorResponsavel: '',
    municipio: caso.municipio,
    talaoBopm: caso.talaoBopm,
    statusCaso: caso.statusCaso,
    nomeCompletoDesaparecido: caso.nomeCompletoDesaparecido,
    sexoGenero: caso.sexoGenero,
    idade: caso.idade,
    faixaEtaria: caso.faixaEtaria,
    cpf: caso.cpf,
    rg: caso.rg,
    nomeMae: caso.nomeMae,
    dataNascimento: caso.dataNascimento,
    dataHoraUltimaVisualizacao: caso.dataHoraUltimaVisualizacao,
    localUltimaVisualizacao: caso.localUltimaVisualizacao,
    roupaUltimaVisualizacao: caso.roupaUltimaVisualizacao,
    meioTransporte: caso.meioTransporte,
    dadosVeiculo: caso.dadosVeiculo,
    fotoDisponivel: caso.fotoDisponivel,
    linkFoto: caso.linkFoto,
    telefoneDesaparecido: caso.telefoneDesaparecido,
    dispositivoLigado: caso.dispositivoLigado,
    camerasResidencia: caso.camerasResidencia,
    camerasUltimoLocal: caso.camerasUltimoLocal,
    aptoCabineVerde: caso.aptoCabineVerde,
    nomeSolicitante: caso.nomeSolicitante,
    vinculoSolicitante: caso.vinculoSolicitante,
    telefoneSolicitante: caso.telefoneSolicitante,
    vulnerabilidade: caso.vulnerabilidade,
    condicaoMentalCognitivaComportamental: caso.condicaoMentalCognitivaComportamental,
    limitacaoFisica: caso.limitacaoFisica,
    usoMedicacaoEssencial: caso.usoMedicacaoEssencial,
    usoAlcoolOutrasDrogas: caso.usoAlcoolOutrasDrogas,
    historicoDesaparecimentoAnterior: caso.historicoDesaparecimentoAnterior,
    conflitoPrevio: caso.conflitoPrevio,
    suspeitaCrime: caso.suspeitaCrime,
    locaisHabituais: caso.locaisHabituais,
    buscasPreliminares: caso.buscasPreliminares,
    classificacaoRisco: caso.classificacaoRisco,
    prioridade: caso.prioridade,
    acaoSugerida: caso.acaoSugerida,
    localizado: caso.statusCaso === 'Localizado' || caso.statusCaso === 'Encerrado',
    dataHoraLocalizacao: '',
    formaLocalizacao: '',
    encerrado190: caso.statusCaso === 'Encerrado',
    numeroBo: '',
    observacoesOperacionais: caso.observacoesOperacionais
  };

  return {
    aba: 'Desaparecidos',
    colunas: [...colunasDesaparecidos],
    dados,
    valores: colunasDesaparecidos.map((coluna) => dados[coluna])
  };
};
