import type { CasoCompleto, SheetPayload } from '../types/case.js';

export const gerarPayloadSheets = (caso: CasoCompleto): SheetPayload => ({
  aba: 'Desaparecidos',
  valores: [
    caso.dataHoraRegistro,
    caso.municipio,
    caso.talaoBopm,
    caso.nomeCompletoDesaparecido,
    caso.sexoGenero,
    caso.idade,
    caso.cpf,
    caso.rg,
    caso.nomeMae,
    caso.dataNascimento,
    caso.fotoDisponivel,
    caso.linkFoto,
    caso.telefoneDesaparecido,
    caso.dispositivoLigado,
    caso.dataHoraUltimaVisualizacao,
    caso.localUltimaVisualizacao,
    caso.roupaUltimaVisualizacao,
    caso.meioTransporte,
    caso.dadosVeiculo,
    caso.nomeSolicitante,
    caso.vinculoSolicitante,
    caso.telefoneSolicitante,
    caso.vulnerabilidade,
    caso.condicaoMentalCognitivaComportamental,
    caso.limitacaoFisica,
    caso.usoMedicacaoEssencial,
    caso.usoAlcoolOutrasDrogas,
    caso.historicoDesaparecimentoAnterior,
    caso.conflitoPrevio,
    caso.suspeitaCrime,
    caso.locaisHabituais,
    caso.buscasPreliminares,
    caso.camerasResidencia,
    caso.camerasUltimoLocal,
    caso.observacoesOperacionais,
    caso.statusCaso,
    caso.faixaEtaria,
    caso.classificacaoRisco,
    caso.prioridade,
    caso.acaoSugerida,
    caso.aptoCabineVerde
  ]
});
