import type { CasoCompleto, SheetPayload } from '../types/case.js';

const colunasDesaparecidos = [
  'dataHoraRegistro',
  'municipio',
  'talaoBopm',
  'nomeCompletoDesaparecido',
  'sexoGenero',
  'idade',
  'faixaEtaria',
  'cpf',
  'rg',
  'nomeMae',
  'dataNascimento',
  'fotoDisponivel',
  'linkFoto',
  'telefoneDesaparecido',
  'dispositivoLigado',
  'dataHoraUltimaVisualizacao',
  'localUltimaVisualizacao',
  'roupaUltimaVisualizacao',
  'meioTransporte',
  'dadosVeiculo',
  'nomeSolicitante',
  'vinculoSolicitante',
  'telefoneSolicitante',
  'vulnerabilidade',
  'condicaoMentalCognitivaComportamental',
  'limitacaoFisica',
  'usoMedicacaoEssencial',
  'usoAlcoolOutrasDrogas',
  'historicoDesaparecimentoAnterior',
  'conflitoPrevio',
  'suspeitaCrime',
  'locaisHabituais',
  'buscasPreliminares',
  'camerasResidencia',
  'camerasUltimoLocal',
  'classificacaoRisco',
  'prioridade',
  'acaoSugerida',
  'aptoCabineVerde',
  'observacoesOperacionais',
  'statusCaso'
] as const;

export const gerarPayloadSheets = (caso: CasoCompleto): SheetPayload => {
  const dados = {
    dataHoraRegistro: caso.dataHoraRegistro,
    municipio: caso.municipio,
    talaoBopm: caso.talaoBopm,
    nomeCompletoDesaparecido: caso.nomeCompletoDesaparecido,
    sexoGenero: caso.sexoGenero,
    idade: caso.idade,
    faixaEtaria: caso.faixaEtaria,
    cpf: caso.cpf,
    rg: caso.rg,
    nomeMae: caso.nomeMae,
    dataNascimento: caso.dataNascimento,
    fotoDisponivel: caso.fotoDisponivel,
    linkFoto: caso.linkFoto,
    telefoneDesaparecido: caso.telefoneDesaparecido,
    dispositivoLigado: caso.dispositivoLigado,
    dataHoraUltimaVisualizacao: caso.dataHoraUltimaVisualizacao,
    localUltimaVisualizacao: caso.localUltimaVisualizacao,
    roupaUltimaVisualizacao: caso.roupaUltimaVisualizacao,
    meioTransporte: caso.meioTransporte,
    dadosVeiculo: caso.dadosVeiculo,
    nomeSolicitante: caso.nomeSolicitante,
    vinculoSolicitante: caso.vinculoSolicitante,
    telefoneSolicitante: caso.telefoneSolicitante,
    vulnerabilidade: caso.vulnerabilidade,
    condicaoMentalCognitivaComportamental: caso.condicaoMentalCognitivaComportamental,
    limitacaoFisica: caso.limitacaoFisica,
    usoMedicacaoEssencial: caso.usoMedicacaoEssencial,
    usoAlcoolOutrasDrogas: caso.usoAlcoolOutrasDrogas,
    historicoDesaparecimentoAnterior: caso.historicoDesaparecimentoAnterior,
    conflitoPrevio: caso.conflitoPrevio,
    suspeitaCrime: caso.suspeitaCrime,
    locaisHabituais: caso.locaisHabituais,
    buscasPreliminares: caso.buscasPreliminares,
    camerasResidencia: caso.camerasResidencia,
    camerasUltimoLocal: caso.camerasUltimoLocal,
    classificacaoRisco: caso.classificacaoRisco,
    prioridade: caso.prioridade,
    acaoSugerida: caso.acaoSugerida,
    aptoCabineVerde: caso.aptoCabineVerde,
    observacoesOperacionais: caso.observacoesOperacionais,
    statusCaso: caso.statusCaso
  };

  return {
    aba: 'Desaparecidos',
    colunas: [...colunasDesaparecidos],
    dados,
    valores: colunasDesaparecidos.map((coluna) => dados[coluna])
  };
};
